import { Project, Skill } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'vision-distill',
    number: '01',
    category: 'COMPUTER VISION',
    title: 'VisionDistill',
    description: 'Lightweight computer vision pipeline using knowledge distillation to compress high-capacity teacher models into fast edge-ready student models.',
    image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&q=80&w=1200',
    tech: ['PYTORCH', 'OPENCV', 'DISTILLATION'],
    color: 'primary',
    github: 'https://github.com/rahulbharathi1921/VisionDistill',
    metrics: [
      { label: 'Compression', value: '4x' },
      { label: 'Accuracy Drop', value: '<1.2%' },
    ],
  },
  {
    id: 'voice-distill',
    number: '02',
    category: 'SPEECH AI',
    title: 'VoiceDistill',
    description: 'Real-time speech command recognition system with distilled acoustic models designed for low-resource hardware and responsive desktop workflows.',
    image: 'https://images.unsplash.com/photo-1761311984305-8cdd650d5b26?auto=format&fit=crop&q=80&w=1200',
    tech: ['PYTORCH', 'SPEECHBRAIN', 'EDGE INFERENCE'],
    color: 'secondary',
    github: 'https://github.com/rahulbharathi1921/VoiceDistill',
  },
  {
    id: 'trading-rag-bot',
    number: '03',
    category: 'NLP & RAG',
    title: 'Trading-rag-bot',
    description: 'Local-first finance assistant powered by RAG that chats with trading books and PDFs using Ollama, without external API dependencies.',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=1200',
    tech: ['LANGCHAIN', 'OLLAMA', 'FAISS'],
    color: 'tertiary',
    github: 'https://github.com/rahulbharathi1921/Trading-rag-bot',
  },
  {
    id: 'pdf-rag-chatbot',
    number: '04',
    category: 'NLP & RAG',
    title: 'PDF-RAG-CHATBOT',
    description: 'Streamlit-based retrieval chatbot for PDF workflows with environment-driven config, chunking pipelines, and semantically grounded responses.',
    image: 'https://images.unsplash.com/photo-1583955746149-71a61419d759?auto=format&fit=crop&q=80&w=1200',
    tech: ['STREAMLIT', 'LANGCHAIN', 'RAG'],
    color: 'primary',
    github: 'https://github.com/rahulbharathi1921/PDF-RAG-CHATBOT',
  },
  {
    id: 'stockmind-ai',
    number: '05',
    category: 'MACHINE LEARNING',
    title: 'StockMind-AI',
    description: 'AI-driven stock analytics dashboard with ML forecasting, interactive visualizations, and model-backed market trend interpretation.',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=1200',
    tech: ['XGBOOST', 'PLOTLY', 'STREAMLIT'],
    color: 'secondary',
    github: 'https://github.com/rahulbharathi1921/StockMind-AI',
  },
  {
    id: 'minimal-rag-bot',
    number: '06',
    category: 'LOCAL LLM SYSTEMS',
    title: 'minimal-rag-bot',
    description: 'Minimal RAG stack for ingesting documents and chatting with local LLMs, built for reproducibility and low setup overhead.',
    image: 'https://images.unsplash.com/photo-1584169417032-d34e8d805e8b?auto=format&fit=crop&q=80&w=1200',
    tech: ['LANGCHAIN', 'FAISS', 'LOCAL LLM'],
    color: 'tertiary',
    github: 'https://github.com/rahulbharathi1921/minimal-rag-bot',
  },
  {
    id: 'desktop-voice-assistant',
    number: '07',
    category: 'VOICE AUTOMATION',
    title: 'Desktop-Voice-Assistant',
    description: 'Windows-focused assistant with configurable commands and safety-guarded system actions for practical day-to-day automation.',
    image: 'https://images.unsplash.com/photo-1519558260268-cde7e03a0152?auto=format&fit=crop&q=80&w=1200',
    tech: ['PYTHON', 'VOICE COMMANDS', 'AUTOMATION'],
    color: 'primary',
    github: 'https://github.com/rahulbharathi1921/Desktop-Voice-Assistant',
  },
  {
    id: 'offline-studio-ai',
    number: '08',
    category: 'GENERATIVE AI',
    title: 'Offline-Studio-AI',
    description: 'Private local image stylizer for cinematic and anime-inspired outputs using Stable Diffusion workflows and offline model execution.',
    image: 'https://images.unsplash.com/photo-1704964969056-0c6d7caf7af8?auto=format&fit=crop&q=80&w=1200',
    tech: ['STABLE DIFFUSION', 'PYTHON', 'LOCAL INFERENCE'],
    color: 'secondary',
    github: 'https://github.com/rahulbharathi1921/Offline-Studio-AI',
  },
  {
    id: 'miui-media-decryptor',
    number: '09',
    category: 'SECURITY & UTILITY',
    title: 'MIUI-media-decryptor',
    description: 'Batch decryption toolkit for MIUI encrypted media with controlled cleanup behavior and operator-friendly CLI execution.',
    image: 'https://images.unsplash.com/photo-1548092372-0d1bd40894a3?auto=format&fit=crop&q=80&w=1200',
    tech: ['PYTHON', 'CRYPTOGRAPHY', 'CLI'],
    color: 'tertiary',
    github: 'https://github.com/rahulbharathi1921/MIUI-media-decryptor',
  },
  {
    id: 'miui-vault-decryptor',
    number: '10',
    category: 'FORENSICS TOOLING',
    title: 'MIUI-vault-decryptor',
    description: 'Forensic-style utility that decrypts MIUI vault files (`.lsa`, `.lsav`) and restores media formats through signature-aware processing.',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1200',
    tech: ['PYTHON', 'FILE FORENSICS', 'AUTOMATION'],
    color: 'primary',
    github: 'https://github.com/rahulbharathi1921/MIUI-vault-decryptor',
  },
  {
    id: 'neonlearn-studio',
    number: '11',
    category: 'FRONTEND SYSTEM DESIGN',
    title: 'neonlearn-studio-web-design-demo',
    description: 'Enterprise-style multi-page education platform demo with modular architecture, polished motion language, and theme-driven UI systems.',
    image: 'https://images.unsplash.com/photo-1765020553499-1ec9aeb21298?auto=format&fit=crop&q=80&w=1200',
    tech: ['HTML', 'CSS', 'JAVASCRIPT'],
    color: 'secondary',
    github: 'https://github.com/rahulbharathi1921/neonlearn-studio-web-design-demo',
  },
  {
    id: 'medicare-hms',
    number: '12',
    category: 'ENTERPRISE APPLICATIONS',
    title: 'medicare-hms',
    description: 'Comprehensive hospital management system covering appointments, billing, doctor workflows, departments, and analytics dashboards.',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=1200',
    tech: ['JAVASCRIPT', 'HTML5', 'CSS3'],
    color: 'tertiary',
    github: 'https://github.com/rahulbharathi1921/medicare-hms',
  },
];

export const SKILLS: Skill[] = [
  {
    domain: '01',
    title: 'AI MODEL EFFICIENCY',
    description: 'Designing distillation and optimization pipelines that preserve quality while reducing compute and memory cost.',
    icon: 'Cpu',
    tags: ['DISTILLATION', 'EDGE AI', 'OPTIMIZATION'],
  },
  {
    domain: '02',
    title: 'RAG & LOCAL LLM',
    description: 'Building retrieval-augmented assistants using local inference stacks for privacy-first and API-independent deployments.',
    icon: 'Brain',
    tags: ['LANGCHAIN', 'OLLAMA', 'FAISS'],
  },
  {
    domain: '03',
    title: 'ML FOR FINANCE',
    description: 'Creating predictive and analytical workflows for time-series, market signals, and ML-backed dashboarding.',
    icon: 'BarChart',
    tags: ['XGBOOST', 'PLOTLY', 'SCIKIT-LEARN'],
  },
  {
    domain: '04',
    title: 'VOICE & DESKTOP AI',
    description: 'Implementing command-oriented voice interfaces and desktop automation systems with reliable, low-latency behavior.',
    icon: 'Mic',
    tags: ['SPEECH', 'AUTOMATION', 'PYTHON'],
  },
  {
    domain: '05',
    title: 'ENTERPRISE FRONTEND',
    description: 'Architecting modular, responsive multi-page products with strong visual systems and production-style code organization.',
    icon: 'Globe',
    tags: ['UI SYSTEMS', 'PWA', 'PERFORMANCE'],
  },
  {
    domain: '06',
    title: 'SECURITY TOOLING',
    description: 'Developing robust CLI utilities for media recovery, decryption workflows, and system-level automation.',
    icon: 'Shield',
    tags: ['FORENSICS', 'CRYPTOGRAPHY', 'CLI'],
  },
];
